### PR TITLE
The testBundle was ignored for json files.

### PR DESCRIPTION
**Pull request by marhas**

### CODE REVIEW

**Comment by brockboland** [comment]
Oh hey! We haven't been intentionally ignoring you: it seems I didn't have notifications enabled on this repo for some reason. I'll take a look at this when I can, though I'd like to get the build working again first.

**Comment by brockboland** [comment]
Travis is back in action. @vokal/ios-developers anyone else want to take a look at this one?

**Comment by brockboland** [comment]
@vokal/ios-developers if anyone wants to object to this one, kindly do so by EOD Thursday, or else I'm merging it.

**Comment by designatednerd** [comment]
@brockboland same way it's being done in the http files lookup.

**Comment by brockboland** [comment]
Thanks @marhas!

**Pull request merged**
