### PR TITLE
Adjusting Content-Type header testing

### PR DESCRIPTION
**Pull request by vokal-isaac**
@vokal/ios-developers Code review please?

Also, please tag as `2.0.3` after the merge and `pod trunk push` (or maybe I can do that part).

### CODE REVIEW

**Comment by seanwolter** [comment]
Good to pull pending our man Travis

**Comment by brockboland** [comment]
Travis is having a day.

**Comment by vokal-isaac** [comment]
Travis Status: http://www.traviscistatus.com/incidents/s3623f034mmy

**Comment by vokal-isaac** [comment]
@chillpop Are you free to merge & tag?

**Comment by chillpop** [comment]
tagged and merged.  let me know if you need a `push` too

**Comment by vokal-isaac** [comment]
ty

**Pull request merged**
