### PR TITLE
Add test targets for tvOS and OSX

### PR DESCRIPTION
**Pull request by chillpop**
@vokal/ios-developers, this should be the last PR to do with adding support for tvOS.

I added two empty applications to run the tests on tvOS and OSX.

There's not code to review, but relevant changes to the .travis.yml and Podfile. Thankfully, both are at the top of the diff.

### CODE REVIEW

**Comment by vokal-isaac** [comment]
LGTM, pending Travis.

**Comment by brockboland** [comment]
LGTM, but tvOS and OS X builds may have stalled out

**Comment by brockboland** [comment]
Yeah, they had just stalled. I restarted both after 10 minutes without output and they passed. GTP!

**Comment by chillpop** [comment]
tagged and `pod trunk push`'d

**Pull request merged**
